### ISSUE TITLE
_set_ctrl() 

### ISSUE THREAD

**Issue by cepr** [mitshell/CC2531#2]
It may not be a bug, but I suspect a copy/paste issue between _get_ctrl() and _set_ctrl().

The method _set_ctrl() in CC2531.py, line 216 is calling libusb with `l` as the `data` argument. I do not know Python very well, so I am not sure how an integer gets converted into a byte array.

Would you have a pcap capture of the USB transfers when running the Windows application ?

https://github.com/mitshell/CC2531/blob/master/CC2531/CC2531.py#L216

**Comment by mitshell** [comment]
The _set_ctrl() is using python-libusb1 USBDeviceHandle.controlWrite(),
which itself passes the data input variable to create_binary_buffer().
This last one takes care to possibly cast the data input variable, if
needed.
The type of the data input variable depends of the request_type input
variable.

I cannot found any remaining USB pcap yet, I will check further if I can
find and provide one to you.

2015-02-12 23:11 GMT+01:00 Cedric notifications@github.com:

**Comment by vpelletier** [comment]
> This last one takes care to possibly cast the data input variable, if
> needed.

This is mainly intended for read functions, actually, although I do not intend to change this. For write functions, it means that a buffer of given size get allocated and sent to the device (hopefully containing only null bytes, depending on how ctypes - or deeper levels - allocate it).
So if you checked it is properly initialised and actually want to send all-zeros, it's fine - although my personal preference would be something like `"\x00" * l` to make code less surprising.

**Comment by cepr** [comment]
OK, I am assuming for now that I can replace the length by 0.
I am writing a minimal C program to capture packets, and I wanted to make sure I understood want the function was actually doing.
Thank you for this program, it is very useful to me!
