### ISSUE TITLE
LIBUSB_ERROR_TIMEOUT [-7] during "getManufacturer()"

### ISSUE THREAD

**Issue by dwu-zingbox** [mitshell/CC2531#3]
Mitshell,

I'm using Ubuntu 14.10. x64. sniffer.py reports "[CC2531] cannot open USB device through libusb: add yourself in the "root" group or make an udev rule" even running under sudo. I then trace the error detail to libusb1 module and found it was LIBUSB_ERROR_TIMEOUT [-7].

-Dennis

**Comment by mitshell** [comment]
Getting a timeout from the very first USB request generally means you do not have the right to access the USB port. You could verify that:
- you really have the right of the root user (not sudo-ing python, but just getting root and then starting the app).
- there is no kernel module already loaded to handle your CC2531 dongle (in this case, you may have to unload it manually 1st).
