### ISSUE TITLE
LIBUSB_ERROR_PIPE

### ISSUE THREAD

**Issue by Otxandio** [mitshell/CC2531#5]
Good morning,

I'm trying to use the CC2531 with a Beaglebone running Debian for the first time. Previously I used a Beaglebone running Angstrom with the CC2531 with success. Now I'm getting this error and all my efforts to solve it are in vane. Ant help would be very appreciate  

root@beaglebone:~/CC2531/CC2531# python ./sniffer.py -c 25
[GPS_reader][ERR] cannot open /dev/ttyUSB0
[CC2531][17168] driving CC2531 USB Dongle @ USB bus 1 & address 2, with serial 17168
Traceback (most recent call last):
  File "./sniffer.py", line 255, in <module>
    main()
  File "./sniffer.py", line 240, in main
    ccs = prepare_receiver(chans)
  File "./sniffer.py", line 123, in prepare_receiver
    ss = [receiver(cc) for cc in ccs]
  File "/root/CC2531/CC2531/receiver.py", line 101, in **init**
    self._cc.init()
  File "/root/CC2531/CC2531/CC2531.py", line 232, in init
    self._set_config(0)
  File "/root/CC2531/CC2531/CC2531.py", line 182, in _set_config
    ret = self.com.controlWrite(0x00, 9, c, 0, '\0')
  File "build/bdist.linux-armv7l/egg/usb1.py", line 1350, in controlWrite
    sizeof(data), timeout)
  File "build/bdist.linux-armv7l/egg/usb1.py", line 1329, in _controlTransfer
    mayRaiseUSBError(result)
  File "build/bdist.linux-armv7l/egg/usb1.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "build/bdist.linux-armv7l/egg/usb1.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]

**Comment by mitshell** [comment]
It looks like you are not allowed to write to the USB port. I have no idea why it fails here, maybe ensure no other driver is trying to control the dongle ?

**Comment by Otxandio** [comment]
OK, thanks for the quick answer mitshell. I've just checked that no driver is bound to the dongle. 

root@beaglebone:~/CC2531/CC2531# usb-devices
T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=32 #Cfgs=  1
P:  Vendor=0451 ProdID=16ae Rev=43.10
S:  Manufacturer=Texas Instruments
S:  Product=CC2531 USB Dongle
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=ff(vend.) Sub=ff Prot=ff **Driver=(none)**

Should some driver must appear there or it's correct?

**Comment by Otxandio** [comment]
Still stuck with the problem. Unbinding the driver the error changes:
root@beaglebone:~# echo -n "1-1" > /sys/bus/usb/drivers/usb/unbind
root@beaglebone:~/CC2531/CC2531# python ./sniffer.py -c 25
[GPS_reader][ERR] cannot open /dev/ttyUSB0
[CC2531][13139] driving CC2531 USB Dongle @ USB bus 1 & address 2, with serial 13139
Traceback (most recent call last):
  File "./sniffer.py", line 255, in <module>
    main()
  File "./sniffer.py", line 240, in main
    ccs = prepare_receiver(chans)
  File "./sniffer.py", line 104, in prepare_receiver
    ccs = map(CC2531, get_CC2531())
  File "/root/CC2531/CC2531/CC2531.py", line 147, in **init**
    self.open()
  File "/root/CC2531/CC2531/CC2531.py", line 165, in open
    self.com.claimInterface(self.IF)
  File "build/bdist.linux-armv7l/egg/usb1.py", line 1183, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "build/bdist.linux-armv7l/egg/usb1.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "build/bdist.linux-armv7l/egg/usb1.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]

I cannot bind the dongle to any other driver, only to usb driver. Any advice?

**Comment by mitshell** [comment]
Sorry, but I have no idea why it fails. Maybe try, after a fresh plugin of
the dongle on the beaglebone, to determine if any driver take control over
it automatically, e.g. a serial link emulator driver or some other generic
driver for USB peripheral... Check with standard Linux command: lsusb -v,
lsmod / modprobe / modinfo, /sys/bus/usb/devices...
/sys/kernel/debug/usb/devices... /proc/bus/usb/devices... directories and
files.

Let me know if you find a solution to the problem.
Regards
Benoit

2016-09-06 11:41 GMT+02:00 Otxandio notifications@github.com:

**Comment by Otxandio** [comment]
I've tried a fresh installation of Angstrom and the result is the same. That's quite odd because I have another Beaglebone with the same SO version and the CC2531 works perfectly on it. Still trying to find a solution. 

So far I found the same error using Ubuntu, Debian and Angstron in Beaglebone and Ubuntu in a laptop.

**Comment by vpelletier** [comment]
Hello, python-libusb1 developer here (lurking on a few projects which use my module).

I think you should ask on the [libusb mailing list](https://lists.sourceforge.net/lists/listinfo/libusb-devel), this looks like the kind of low-level issue they may know of.
To write the report mail you may want to build libusb with verbose logging enabled (python-libusb1 follows LD_LIBRARY_PATH semantics so you can use a local build easily) and enabling it (`USBContext.setDebug`, see also [libusb_set_debug documentation](http://libusb.sourceforge.net/api-1.0/group__lib.html#ga5f8376b7a863a5a8d5b8824feb8a427a)), and maybe use ltrace to avoid having to guide them through all the python details (or maybe to discover something weird on the python level).

**Comment by Otxandio** [comment]
OK, thanks a lot vpelletier. I'll proceed as you say.

**Comment by Otxandio** [comment]
I've built the last release of libusb using the option --enable-debug-log end the error output is just the same. I'm a little bit lost, how can I obtain more accurate info to write the  report mail? I'm very sorry for my lack of skills, my apologies.  

P.S. Tested in Fedora too with the same result.

**Comment by vpelletier** [comment]
There is one more step before the library outputs debug logging, it is by calling "setDebug" on the usb context in python. From a very quick look into CC2531 source it seems you should add:

``` python
    ctx.setDebug(usb1.LOG_LEVEL_DEBUG)
```

in [CC2531.py](https://github.com/mitshell/CC2531/blob/master/CC2531/CC2531.py#L73) (right after creating the context).
Someone happens to have recently [reported an issue on libusb mailing list](https://sourceforge.net/p/libusb/mailman/libusb-devel/thread/CAKM5sT-vFbH2Avp6VR1644SM%2Bp%3DYmM2b_fmWNGaTP4gt%3D9Cz9w%40mail.gmail.com/#msg35350660) when trying to use a device with verbose logging - and from python too (although with another wrapper, pyUSB). By quickly browsing the thread you should get an idea of what may be useful to include in your report.

**Comment by Otxandio** [comment]
Oh, I see. I read about setDebug but I didn't know where I should add it. 

Thanks a lot for your help and for enhancing my knowledge. And now, get to work!

**Comment by Otxandio** [comment]
Hello again folks,

I've sent the email to libusb mailing list, it's waiting for approval. 

More info that can be helpful. I've got another Beaglebone where the system is working. The version of the packages in that one are:
Angstrom v2012.12
python-core 2.7.3-r0.3.7
libusb1 version 1.0.9-r1.3
python-libusb1-1.3.0
pyserial-release2_4

Sadly I tried to recreate that environment in the new Beaglebone without success. However, the error is slightly different.

root@beaglebone:~/CC2531/CC2531# python ./sniffer.py -c 25
[GPS_reader][ERR] cannot open /dev/ttyUSB0
[CC2531][13139] driving CC2531 USB Dongle @ USB bus 1 & address 2, with serial 13139
Traceback (most recent call last):
  File "./sniffer.py", line 255, in <module>
    main()
  File "./sniffer.py", line 240, in main
    ccs = prepare_receiver(chans)
  File "./sniffer.py", line 123, in prepare_receiver
    ss = [receiver(cc) for cc in ccs]
  File "/home/root/CC2531/CC2531/receiver.py", line 101, in **init**
    self._cc.init()
  File "/home/root/CC2531/CC2531/CC2531.py", line 232, in init
    self._set_config(0)
  File "/home/root/CC2531/CC2531/CC2531.py", line 182, in _set_config
    ret = self.com.controlWrite(0x00, 9, c, 0, '\0')
  File "/usr/lib/python2.7/site-packages/usb1.py", line 1145, in controlWrite
    sizeof(data), timeout)
  File "/usr/lib/python2.7/site-packages/usb1.py", line 1125, in _controlTransfer
    raise libusb1.USBError(result)
libusb1.USBError: LIBUSB_ERROR_PIPE [-9]

Looks like the problem is clearly related with Python. Any other package that could be important for this matter?

**Comment by mitshell** [comment]
OK, my fault, commit b24652c4 introduced an error on a controlWrite() operation. Has been corrected now. Sorry for that

**Comment by Otxandio** [comment]
Thank you very much mitshell. The problem is solved with the new version. 
I really appreciate all your help pals. 
Best regards.
