### ISSUE TITLE
CC2531 with Raspberry PI?

### ISSUE THREAD

**Issue by kbalint** [mitshell/CC2531#6]
Hi, I'm trying to use your code on Raspi. I've changed gps.py to use /dev/ttyUSB0 -> /dev/ttyAMA0, but got the following error:

>$  python ./sniffer.py -d 3 -p 5 -f
>[sniffer]  command line arguments:
>Namespace(chans=[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26], debug=3, file=True, 
>filesock=False, gps='/dev/ttyUSB0', ip='localhost', nofcschk=False, period=5.0, silent=False)
>[interpreter] server listening on ['localhost', 2154]
>[GPS_reader][ERR] cannot open /dev/ttyAMA0
>[sniffer]  no CC2531 dongles found`

when I do lsusb, it knows the device:

>$ lsusb
>Bus 001 Device 005: ID 0451:16ae Texas Instruments, Inc.
>Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
>Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
>Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

however usb-devices says the following:

>T:  Bus=01 Lev=02 Prnt=02 Port=03 Cnt=02 Dev#=  5 Spd=12  MxCh= 0
>D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=32 #Cfgs=  1
>P:  Vendor=0451 ProdID=16ae Rev=96.62
>S:  Manufacturer=Texas Instruments
>S:  Product=CC2531 USB Dongle
>C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
>I:  If#= 0 Alt= 0 #EPs= 1 Cls=ff(vend.) Sub=ff Prot=ff Driver=(none)`

could the Driver=(none) part be a problem? What am I missing? Thanks!

**Comment by mitshell** [comment]
Hello,

did you ensure the current user has access to USB devices ? Did you set a
udev rule for this ? Or did you run as root ? (did you read the readme ? :)
I guess it is OK if Linux has not loaded any driver for your dongle.
Otherwise, the sniffer program could not access it through libusb1.


2018-09-22 16:06 GMT+02:00 Balint Kardos <notifications@github.com>:

**Comment by kbalint** [comment]
Hi, thanks for your reply and help, it's now working!
Running with root (and setting up python properly for root on raspi) solved my problem.

**Comment by mdshoaibansari** [comment]
Hi @kbalint  , can help me how to use this to capture network using TI CC2531.
From weeks , I am searching in internet as well as in chatgpt how to connect to ti cc2531 . but not getting the required output.
