### ISSUE TITLE
my linux can't not find cc2531 dongle

### ISSUE THREAD

**Issue by jbgod** [mitshell/CC2531#9]
my cc2531 dongle can only use in windows,my linux can't find the driver for cc2531.
i had try to update my kernel configure with ti serial,but i still can't use it in linux
could you give me a firmware of cc2531 used by this project

**Comment by mitshell** [comment]
I don't have any firmware from TI. This project was developed to use CC2531 on Linux out of the box (with their default TI sniffer firmware), without the need for any driver on the Linux side.

**Comment by jbgod** [comment]
i can't find the module parsers in my python3.6
